services:
    devcatops:
        image: devcatops
        build: ./
        restart: unless-stopped
        env_file: .env
        ports:
            - 3000:3000
        volumes:
            - uploads:${UPLOAD_FOLDER}
    mariadb:
        image: mariadb
        restart: unless-stopped
        env_file: .env
        volumes:
        - data:/var/lib/mysql
    classifi-cat-ion:
        image: classifi-cat-ion
        ports:
            - 5000:5000
        restart: unless-stopped

volumes:
  uploads:
  data: