name: Run build and tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    name: Run build and tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - run: pnpm install --frozen-lockfile
    - run: pnpx prisma generate
    - run: pnpm lint
    - run: pnpm test
    - run: pnpm build